### ISSUE TITLE
Script fails with shortcodes

### ISSUE THREAD

**Issue by joenas** [andy-pi/rpi-sms-gateway#1]
Hey. First of all, thanks for an awesome [guide](https://andypi.co.uk/2017/06/24/raspberry-pi-sms-to-email-gateway-part-3/)! 
I got my `gammu` set up today and I wanted to do something similar to yours, except I post to an instance of [huginn](https://github.com/huginn/huginn) instead :)

When testing your script with Twitter I noticed a minor bug. They use short codes as the sender and for some reason the name has a trailing space, which makes the script fail. 
I changed to `number = re.match(r'^IN\d+_\d+_\d+_(.*)_\d+\.txt', os.path.split(files[0])[1]).group(1)` and now it works. That's `(.*)` for matching the sender/number. 

On another note, got any advice for how to catch similar errors, so my smses wont go unnoticed?

**Comment by andy-pi** [comment]
Hi - thanks a lot for trying it out!

The regex is basically cribbed directly from the gammu docs to grab the number from the filename in the inbox - to be honest not really my forté. 
Currently given the example below it will strip out the number between the 3rd and 4th underscores:
IN20170814_190405_00_+441906803026_00.txt

But I am correct in saying that the filename you'd be getting is something like:
IN20170814_190405_00_8888 TWITTER_00.txt

I wonder if all shortcodes are like this?

With regards to error handling, that is the major flaw in this project, there is non! I'm not quite sure how that script would fail in this case, apart from to give a blank number? What happened in your case? I think to make sure you catch errors like this you'd probably need to send yourself an alert everytime the script runs (that is to say, every time you get an sms, since the script is triggered by receipt of sms). e.g if get_message() function is throwing an exception, something like

`try:  `
&nbsp;&nbsp;&nbsp;&nbsp;`number,text=get_message()  `
`except:  `
&nbsp;&nbsp;&nbsp;&nbsp;`number=0  `
&nbsp;&nbsp;&nbsp;&nbsp;`text='ERROR RECEIVING SMS'`

**Comment by joenas** [comment]
> I'm not quite sure how that script would fail in this case, apart from to give a blank number? What happened in your case?

Since the regex doesn't match and the group is empty the script gives a runtime error :)

Also I noticed it's not a space, it's an actual newline (`\n`). Why they (Twitter) would do that I do not know....

**Comment by joenas** [comment]
I've tried the modified script for a couple of days and it works great with both regular numbers and short codes, twitter and instagram for example!

**Comment by joenas** [comment]
Anywho i just noticed you pushed a fix so let's close this!
